apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80           # Service port inside the cluster
      targetPort: 80     # The port the pod is listening on
      nodePort: 32472    # Exposed port on the Kind node (must be 30000-32767)
